### PR TITLE
feat(#103): add Tree column in Tree page table

### LINKED ISSUE #103: Add tree name column on revisions table

### PR DESCRIPTION
**Pull request by lfjnascimento**
Close #103

### CODE REVIEW

**Review by mari1912 — APPROVED** [review]
lgtm

**Comment by WilsonNet** [comment]
image
getting this error in the index page

**Comment by WilsonNet** [comment]
```
chunk-F3TAIX4O.js?v=e267eeec:14032 The above error occurred in the <TreeTableRow> component:

    at TreeTableRow (http://localhost:5173/src/components/Table/TreeTable.tsx:33:20)
    at table
    at div
    at _c (http://localhost:5173/src/components/ui/table.tsx:20:11)
    at div
    at BaseTable (http://localhost:5173/src/components/Table/BaseTable.tsx:20:3)
    at TreeTable (http://localhost:5173/src/components/Table/TreeTable.tsx:89:22)
    at div
    at TreeListingPage (http://localhost:5173/src/components/TreeListingPage/TreeListingPage.tsx:60:28)
    at div
    at Trees (http://localhost:5173/src/pages/Trees.tsx:23:49)
    at MatchInnerImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3669:3)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at MatchImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3612:3)
    at Suspense
    at OutletImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3775:18)
    at div
    at div
    at div
    at component
    at MatchInnerImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3669:3)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
    at MatchImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3612:3)
    at CatchBoundaryImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:1241:5)
    at CatchBoundary (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:1221:32)
    at MatchesInner (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3831:19)
    at Suspense
    at Matches (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4dd

**Comment by WilsonNet** [comment]
more evidence:
image

**Comment by lfjnascimento** [comment]
> ```
> chunk-F3TAIX4O.js?v=e267eeec:14032 The above error occurred in the <TreeTableRow> component:
> 
>     at TreeTableRow (http://localhost:5173/src/components/Table/TreeTable.tsx:33:20)
>     at table
>     at div
>     at _c (http://localhost:5173/src/components/ui/table.tsx:20:11)
>     at div
>     at BaseTable (http://localhost:5173/src/components/Table/BaseTable.tsx:20:3)
>     at TreeTable (http://localhost:5173/src/components/Table/TreeTable.tsx:89:22)
>     at div
>     at TreeListingPage (http://localhost:5173/src/components/TreeListingPage/TreeListingPage.tsx:60:28)
>     at div
>     at Trees (http://localhost:5173/src/pages/Trees.tsx:23:49)
>     at MatchInnerImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3669:3)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at MatchImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3612:3)
>     at Suspense
>     at OutletImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3775:18)
>     at div
>     at div
>     at div
>     at component
>     at MatchInnerImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3669:3)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at SafeFragment (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3589:87)
>     at MatchImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3612:3)
>     at CatchBoundaryImpl (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:1241:5)
>     at CatchBoundary (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:1221:32)
>     at MatchesInner (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4ddec4e3:3831:19)
>     at Suspense
>     at Matches (http://localhost:5173/node_modules/.vite/deps/@tanstack_react-router.js?v=4dd
> ```

Hmm, looks like the backend server wasn't running the updated code. Could you double check please?

**Review by WilsonNet — APPROVED** [review]
worked now on my machine

**Comment by lfjnascimento** [comment]
> worked now on my machine

Almost sure that was a cache thing, if you tested on an old tab the `tree_names` would be `undefined`

**Pull request closed without merging**
